"""add is_read to message table

Revision ID: 593be154a15f
Revises: 651f059276a6
Create Date: 2025-09-12 19:02:49.112341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593be154a15f'
down_revision = '651f059276a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
