"""add line_user_id to user

Revision ID: 61e88e1e636b
Revises: e7fcd56ee5eb
Create Date: 2025-09-12 14:34:49.440319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e88e1e636b'
down_revision = 'e7fcd56ee5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_line_user_id', ['line_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_line_user_id', type_='unique')
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###
