"""add name field to quick_reply table

Revision ID: 648bb432f521
Revises: 593be154a15f
Create Date: 2025-09-12 19:34:44.667691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648bb432f521'
down_revision = '593be154a15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_quick_reply_name'), ['name'], unique=False)
        batch_op.drop_column('scope')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_quick_reply_name'))
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
