"""add picture_url to user

Revision ID: 651f059276a6
Revises: c8890dfa8817
Create Date: 2025-09-12 18:57:02.007537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651f059276a6'
down_revision = 'c8890dfa8817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
