"""Add indexes to Message model

Revision ID: 6a97ab13a75d
Revises: 8a2259b36ecf
Create Date: 2025-09-13 19:52:30.309342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a97ab13a75d'
down_revision = '8a2259b36ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_line_account_id'), ['line_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_message_line_account_id'))

    # ### end Alembic commands ###
