"""add line profile table

Revision ID: 926697d246cd
Revises: 0184fa729838
Create Date: 2025-09-10 16:19:06.340550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926697d246cd'
down_revision = '0184fa729838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_profile',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('picture_url', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('line_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_profile_display_name'), ['display_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_profile_display_name'))

    op.drop_table('line_profile')
    # ### end Alembic commands ###
